### ISSUE TITLE
Design for Adding Phone number + Twilio verification flow

### ISSUE THREAD

**Issue by melchua** [melchua/grateful#32]
## Summary
After the user has logged in, there are two main call to actions:
1. Save a gratitude
2. Add phone number (which includes verification, and then turning setting on to receive texts)

The challenge is how to make this process easy for the user, yet encourage them to do so. 

Let's see what you come up with @glenyingchua

**Comment by glenyingchua** [comment]
Gratitude saving option and storage done.

Working on simple phone verification design.

**Comment by glenyingchua** [comment]
Please see: https://xd.adobe.com/view/765e2211-29f1-41b7-88b7-4e9c8db75d85-230d/

and view GRID option to see start of mock-up for web version.

**Comment by glenyingchua** [comment]
Updated: mock-up of phone verification

**Comment by melchua** [comment]
Web version looks good. As mentioned previously we should communicate on the login as we will not have any login screens now, so phone verification will be need to be reworked. @glenyingchua
