### ISSUE TITLE
Register screen

### ISSUE THREAD

**Issue by melchua** [melchua/grateful#4]

**Comment by glenyingchua** [comment]
![Screen Shot 2021-03-14 at 7.00.32 PM.png](https://images.zenhubusercontent.com/6049a1b8c7bb28d2593e6b77/91e236b2-c296-4b3a-88d3-0bb980fceb8c)

**Comment by melchua** [comment]
Hey thanks for doing the login/logout screens. The way we're doing it now, I think we're limited with the designs for login.
Let me know when you have a sec to go through what we have so far. I think the most customization we'll do with login is a custom logo and some basic styling.

@glenyingchua
