### ISSUE TITLE
Main app screen

### ISSUE THREAD

**Issue by melchua** [melchua/grateful#6]

**Comment by glenyingchua** [comment]
![Screen Shot 2021-03-14 at 7.04.03 PM.png](https://images.zenhubusercontent.com/6049a1b8c7bb28d2593e6b77/77477617-4990-43d9-928d-079aee0a1a3d)

**Comment by glenyingchua** [comment]
![Screen Shot 2021-03-14 at 7.22.25 PM.png](https://images.zenhubusercontent.com/6049a1b8c7bb28d2593e6b77/3828caa7-7b93-406f-b222-e6cb81306e49)

**Comment by glenyingchua** [comment]
Option for scrolling list of past gratitudes which can be edited, deleted, favourited (or "marked"). 

Opting for no hashtags to keep it clean and simple, but gratitudes are still searchable. 

Option for calendar view of gratitudes.

**Comment by melchua** [comment]
Just wondering what the web equivalent will be since that's the part we're developing right now.

**Comment by glenyingchua** [comment]
https://xd.adobe.com/view/765e2211-29f1-41b7-88b7-4e9c8db75d85-230d/
